# Generated by Django 5.2.10 on 2026-03-12 09:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="userprofile_search_gin"
            ),
        ),
    ]
