# Generated by Django 5.2.11 on 2026-02-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_pic",
        ),
    ]
