# Generated by Django 5.2.13 on 2026-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                condition=models.Q(("is_public", True)),
                fields=["user"],
                name="userprofile_public_idx",
            ),
        ),
    ]
