# Generated by Django 5.2.12 on 2026-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userfollower_follower_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userfollower",
            index=models.Index(
                fields=["follower", "status"], name="users_userf_followe_cfe983_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfollower",
            index=models.Index(
                fields=["following", "status"], name="users_userf_followi_544434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfollower",
            index=models.Index(
                fields=["following", "created_at"],
                name="users_userf_followi_92714f_idx",
            ),
        ),
    ]
