# Generated by Django 5.2.11 on 2026-02-25 14:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.UserProfile.avatar_upload_image_path,
            ),
        ),
    ]
