# Generated by Django 5.2.12 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_populate_userprofile_search_vectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="followers_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="following_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
