# Generated by Django 5.2.13 on 2026-04-23 07:57

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_email_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.avatar_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Height in cm.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Weight in kg.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
