# Generated by Django 5.2.12 on 2026-03-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userfollower_users_userf_followe_cfe983_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollower",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_relation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollower",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_relation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
