# Generated by Django 5.2.13 on 2026-04-27 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("block", "Block"),
                            ("manual_review", "Manual review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("flagged", models.BooleanField(default=False)),
                ("categories", models.JSONField(blank=True, default=dict)),
                ("category_scores", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation result",
                "verbose_name_plural": "Moderation results",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="common_mode_content_549be2_idx",
                    ),
                    models.Index(
                        fields=["flagged", "-created_at"],
                        name="common_mode_flagged_5498b6_idx",
                    ),
                ],
            },
        ),
    ]
