# Generated by Django 5.2.12 on 2026-03-08 14:01

import community.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workouts", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional headline for the post.",
                        max_length=300,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from title.",
                        max_length=350,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Main body / caption of the post."),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional single cover/header image.",
                        null=True,
                        upload_to=community.models.post_cover_upload_path,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("workout", "Workout Share"),
                            ("progress", "Progress Update"),
                            ("question", "Question"),
                            ("review", "Review"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers Only"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=20,
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("dislikes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_workout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Attach a workout to this post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_posts",
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(help_text="The comment text.")),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("dislikes_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set to create a reply to another comment.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=community.models.post_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "mkv",
                                    "webm",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order within the post."
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessibility description.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Media",
                "verbose_name_plural": "Post Media",
            },
        ),
        migrations.CreateModel(
            name="PostReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Reaction",
                "verbose_name_plural": "Post Reactions",
            },
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Reaction",
                "verbose_name_plural": "Comment Reactions",
                "indexes": [
                    models.Index(
                        fields=["comment", "reaction_type"],
                        name="community_c_comment_a798db_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "comment"),
                        name="unique_comment_reaction_per_user",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_deleted", "is_archived", "-created_at"],
                name="community_p_is_dele_ca9d03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="community_p_author__c7cd0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "is_archived", "-created_at"],
                name="community_p_visibil_513fc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["post_type", "-created_at"],
                name="community_p_post_ty_d58aee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "parent", "created_at"],
                name="community_c_post_id_490b61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "-created_at"], name="community_c_author__460540_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_deleted", "-created_at"],
                name="community_c_is_dele_5d9dbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "parent"], name="community_c_post_id_f91575_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "-created_at"], name="community_c_post_id_4c58cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postmedia",
            index=models.Index(
                fields=["post", "order"], name="community_p_post_id_22d373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(
                fields=["post", "reaction_type"], name="community_p_post_id_f86415_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postreaction",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_post_reaction_per_user"
            ),
        ),
    ]
