# Generated by Django 5.2.12 on 2026-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="dislikes_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="comments_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="dislikes_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
