# Generated by Django 5.2.12 on 2026-04-14 07:52

import common.validators
import community.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="file",
            field=models.FileField(
                upload_to=community.models.post_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "avi",
                            "mov",
                            "mkv",
                            "webm",
                        ]
                    ),
                    common.validators.validate_media_size,
                    common.validators.validate_real_content_type,
                ],
            ),
        ),
    ]
