# Generated by Django 5.2.13 on 2026-04-17 07:22

import common.validators
import community.models
import django.core.validators
import uuid
from django.db import migrations, models


def backfill_comment_uuids(apps, schema_editor):
    Comment = apps.get_model("community", "Comment")
    for comment in Comment.objects.filter(uuid__isnull=True).only("pk"):
        comment.uuid = uuid.uuid4()
        comment.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_comment_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_comment_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional single cover/header image.",
                null=True,
                upload_to=community.models.post_cover_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif"]
                    ),
                    common.validators.validate_media_size,
                    common.validators.validate_real_content_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(
                help_text="Main body / caption of the post.",
                validators=[django.core.validators.MaxLengthValidator(5000)],
            ),
        ),
    ]
