# Generated by Django 5.2.13 on 2026-04-17 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_alter_comment_uuid_alter_post_cover_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commentreaction",
            index=models.Index(
                fields=["user", "-created_at"], name="commentreaction_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(
                fields=["user", "-created_at"], name="postreaction_user_idx"
            ),
        ),
    ]
