# Generated by Django 5.2.13 on 2026-04-23 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_commentreaction_commentreaction_user_idx_and_more"),
        ("workouts", "0006_seed_muscle_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_deleted", "visibility", "-likes_count", "-created_at"],
                name="feed_popular_idx",
            ),
        ),
    ]
