# Generated by Django 5.2.13 on 2026-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_feed_popular_index"),
    ]

    # Existing rows are grandfathered as ``published`` so the moderation
    # rollout doesn't retroactively hide already-live content. New rows
    # still default to ``pending`` via the model definition — Django's ORM
    # always passes the model default explicitly on INSERT, so the
    # schema-level default below only governs this one-time backfill.
    operations = [
        migrations.AddField(
            model_name="comment",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("error", "Moderation error"),
                ],
                db_index=True,
                default="published",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="requires_manual_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set when the OpenAI call failed all retries and we fell open.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("error", "Moderation error"),
                ],
                db_index=True,
                default="published",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="requires_manual_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set when the OpenAI call failed all retries and we fell open.",
            ),
        ),
    ]
