"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR/".env")

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY must be set to a non-empty value before Django can start."
    )

DEBUG = os.getenv("DEBUG") == "True"

# Strip empties and whitespace so a typo like `ALLOWED_HOSTS=a,,b` doesn't
# leave a silent empty-host entry in the list.
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()]



INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django_extensions",
    "django.contrib.sites", # Required by allauth
    
    # --- Social Auth / OAuth ---
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google", # Google
    # "allauth.socialaccount.providers.apple", # (Commented out until you get your domain)
    
    "dj_rest_auth",
    "dj_rest_auth.registration",
    
    # --- API Tools ---
    "drf_spectacular",
    "corsheaders",
    "rest_framework",
    "storages",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    
    # --- Background Workers & Scheduling ---
    "django_celery_beat", # <-- ADD THIS (For your periodic tasks)

    # --- Local Apps ---
    "common",
    "workouts",
    "community",
    "users",
]

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True, 
    }
}

LOGIN_REDIRECT_URL = '/admin/' 
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # --- ADD THIS LINE ---
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',

   'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',   
        'rest_framework.throttling.UserRateThrottle',   
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'reaction_spam': '20/min',
        'search': '30/min',
        'strict_auth': '5/min',
        # Follow/accept/reject take row-level locks on two UserProfile rows
        # each call. Rate-limit them to stop a single authenticated client
        # from holding locks in a tight loop or flooding the FTS signal path.
        'social_write': '60/min',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Only disable server-side cursors when running behind pgBouncer in transaction
# pooling mode. Direct Postgres connections benefit from server-side cursors for
# the large-result-set queries used by FeedCursorPagination.
USE_PGBOUNCER = os.getenv("USE_PGBOUNCER", "False") == "True"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "gym_hub",
        "USER": "postgres",
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": "localhost",
        "PORT": "5432",
        "DISABLE_SERVER_SIDE_CURSORS": USE_PGBOUNCER,
    }
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
}

# dj-rest-auth: JWT-only, no DRF authtoken.
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "SESSION_LOGIN": False,
    "TOKEN_MODEL": None,
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'users.User'


# Add this to tell Django to look in your new root static folder!
STATICFILES_DIRS = [
    BASE_DIR / "static", 
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", 
    "http://127.0.0.1:3000",
    "https://gymhub-frontend.vercel.app", 
]


MAX_IMAGE_UPLOAD_SIZE = 10 * 1024 * 1024
MAX_VIDEO_UPLOAD_SIZE = 50 * 1024 * 1024
MAX_AVATAR_UPLOAD_SIZE = 5 * 1024 * 1024

# Cap non-file request bodies (JSON/form) and file uploads. Keep comfortably
# below any upstream nginx/ALB limit. Videos use streamed multipart uploads,
# so FILE_UPLOAD_MAX_MEMORY_SIZE only controls the in-memory buffer cutoff
# before Django spills to a TemporaryUploadedFile.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024        # 10 MB JSON/form body
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024         # 5 MB before disk spill
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

CORS_ALLOW_ALL_ORIGINS = False


CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_RESULT_URL", "redis://localhost:6379/1")
CELERY_TASK_IGNORE_RESULT = True  
CELERY_WORKER_CONCURRENCY = 4
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SOFT_TIME_LIMIT = 300  
CELERY_TASK_TIME_LIMIT = 330     


CELERY_TASK_ROUTES = {
    'community.tasks.process_post_media': {'queue': 'media'},
    'community.tasks.purge_*':            {'queue': 'maintenance'},
    'common.tasks.reconcile_counters':    {'queue': 'maintenance'},
    '*':                                   {'queue': 'default'},
}


from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'purge-deleted-posts': {
        'task': 'community.tasks.purge_soft_deleted_posts',
        'schedule': crontab(hour=3, minute=0),
    },
    'purge-deleted-comments': {
        'task': 'community.tasks.purge_soft_deleted_comments',
        'schedule': crontab(hour=3, minute=15),
    },
    'reconcile-counters': {
        'task': 'common.tasks.reconcile_counters',
        'schedule': crontab(hour='*/6', minute=30),
    },
}


# This checks your .env for USE_SECURE_PROXY=True
IS_IN_PRODUCTION = os.environ.get('USE_SECURE_PROXY', 'False') == 'True'

if IS_IN_PRODUCTION:
    # 1. AWS S3 Settings
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
    
    # S3 Specific Behaviors
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600
    AWS_S3_FILE_OVERWRITE = False

    # 2. Static & Media Locations
    # This creates /static/ and /media/ folders inside your S3 bucket
    STATIC_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{STATIC_LOCATION}/'
    
    MEDIA_LOCATION = 'media'
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{MEDIA_LOCATION}/'

    # 3. Storage Backends (Django 4.2+)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": MEDIA_LOCATION,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": STATIC_LOCATION,
            },
        },
    }

    # 4. Production Security Headers
    CORS_ALLOWED_ORIGINS = ["https://gymhub-frontend.vercel.app"]
    CORS_ALLOW_CREDENTIALS = True 
    
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 Year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

else:
    # 1. Local Storage (Saves to your local 'media' and 'static' folders)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # 2. Local URLs
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"

    # 3. Local Development Security (Relaxed)
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
    ]
    CORS_ALLOW_CREDENTIALS = True