# Generated by Django 5.2.11 on 2026-02-24 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Muscle Group",
                "verbose_name_plural": "Muscle Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("cardio", "Cardio"),
                            ("calisthenics", "Calisthenics"),
                            ("weightlifting", "Weightlifting"),
                        ],
                        db_index=True,
                        default="weightlifting",
                        max_length=20,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("compound", "Compound"), ("isometric", "Isometric")],
                        db_index=True,
                        default="compound",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Step-by-step instructions for performing the exercise safely.",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to a demo video (YouTube, etc.).",
                    ),
                ),
                (
                    "equipment_needed",
                    models.CharField(
                        blank=True,
                        help_text="Equipment required, e.g. 'Barbell, Bench' or 'None'.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "muscles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Primary and secondary muscles activated by this exercise.",
                        related_name="exercises",
                        to="workouts.musclegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional thumbnail / cover image for this workout.",
                        null=True,
                        upload_to="workout_covers/",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_index=True,
                        default="private",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_duration_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Estimated total workout duration in minutes.",
                        null=True,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as a reusable template that others can copy.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who created this workout.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Order of this exercise in the workout."
                    ),
                ),
                ("sets", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "reps",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Reps per set (for strength / calisthenics).",
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Load in kilograms.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "duration_sec",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in seconds (for cardio / isometric holds).",
                        null=True,
                    ),
                ),
                (
                    "rest_sec",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Rest between sets in seconds.", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Exercise",
                "verbose_name_plural": "Workout Exercises",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(
                blank=True,
                related_name="workouts",
                through="workouts.WorkoutExercise",
                to="workouts.exercise",
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["exercise_type", "movement_type"],
                name="workouts_ex_exercis_e92480_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutexercise",
            constraint=models.UniqueConstraint(
                fields=("workout", "exercise", "order"),
                name="unique_exercise_order_per_workout",
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["owner", "visibility"], name="workouts_wo_owner_i_686608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["owner", "-created_at"], name="workouts_wo_owner_i_3bd6f4_idx"
            ),
        ),
    ]
