# Generated by Django 5.2.12 on 2026-03-12 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Muscle Group",
                "verbose_name_plural": "Muscle Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("cardio", "Cardio"),
                            ("calisthenics", "Calisthenics"),
                            ("weightlifting", "Weightlifting"),
                        ],
                        db_index=True,
                        default="weightlifting",
                        max_length=20,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("compound", "Compound"),
                            ("isometric", "Isometric"),
                            ("isolation", "Isolation"),
                        ],
                        db_index=True,
                        default="compound",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Step-by-step form instructions.",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, default="", help_text="Link to a demo video."
                    ),
                ),
                (
                    "equipment_needed",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Barbell, Bench' or 'Bodyweight'.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "muscles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Muscles activated by this exercise.",
                        related_name="exercises",
                        to="workouts.musclegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="workout_covers/"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        db_index=True,
                        default="private",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_duration_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Estimated duration in minutes.",
                        null=True,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Reusable template that others can copy.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order (0-indexed)."
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Per-exercise notes for this workout.",
                        max_length=1000,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Exercise",
                "verbose_name_plural": "Workout Exercises",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(
                blank=True,
                related_name="workouts",
                through="workouts.WorkoutExercise",
                to="workouts.exercise",
            ),
        ),
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveSmallIntegerField(
                        help_text="1-indexed set number within this exercise."
                    ),
                ),
                (
                    "reps",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Reps performed (strength / calisthenics).",
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight lifted in the specified unit.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        blank=True,
                        choices=[("KG", "Kilogram"), ("LBS", "Pound")],
                        default="",
                        help_text="Unit of the weight field.",
                        max_length=3,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in seconds (cardio / isometric).",
                        null=True,
                    ),
                ),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="workouts.workoutexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Set",
                "verbose_name_plural": "Workout Sets",
                "ordering": ["set_number"],
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["exercise_type", "movement_type"],
                name="workouts_ex_exercis_e92480_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutexercise",
            constraint=models.UniqueConstraint(
                fields=("workout", "exercise", "order"),
                name="unique_exercise_order_per_workout",
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["owner", "visibility"], name="workouts_wo_owner_i_686608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["owner", "-created_at"], name="workouts_wo_owner_i_3bd6f4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutset",
            constraint=models.UniqueConstraint(
                fields=("workout_exercise", "set_number"),
                name="unique_set_number_per_exercise",
            ),
        ),
    ]
