# Generated by Django 5.2.11 on 2026-03-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutexercise",
            name="duration_sec",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="rest_sec",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="sets",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="weight_kg",
        ),
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "reps",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Reps per set (for strength / calisthenics).",
                        null=True,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KG", "Kilogram"),
                            ("LBS", "Pound"),
                            ("G", "Gram"),
                            ("OZ", "Ounce"),
                            ("ST", "Stone"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Duration in seconds (for cardio / isometric).",
                        null=True,
                    ),
                ),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="workouts.workoutexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Set",
                "verbose_name_plural": "Workout Sets",
                "ordering": ["set_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workout_exercise", "set_number"),
                        name="unique_set_number_per_workout_exercise",
                    )
                ],
            },
        ),
    ]
