# Generated by Django 5.2.10 on 2026-03-12 09:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="exercise_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="workout_search_gin"
            ),
        ),
    ]
