# Generated by Django 5.2.13 on 2026-04-22 13:58

import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_alter_exercise_uuid"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workoutexercise",
            name="unique_exercise_order_per_workout",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="is_template",
        ),
        migrations.AddField(
            model_name="workoutset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="equipment_needed",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of required equipment, e.g., ['barbell', 'bench']",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("cardio", "Cardio"),
                    ("calisthenics", "Calisthenics"),
                    ("weightlifting", "Weightlifting"),
                ],
                default="weightlifting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workoutset",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight lifted in the specified unit.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutexercise",
            constraint=models.UniqueConstraint(
                fields=("workout", "order"), name="unique_exercise_order_per_workout"
            ),
        ),
    ]
