# Generated by Django 5.2.13 on 2026-04-28 07:19

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_seed_muscle_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exercise",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    models.F("name"), name="gin_trgm_ops"
                ),
                name="exercise_name_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    models.F("name"), name="gin_trgm_ops"
                ),
                name="workout_name_trgm",
            ),
        ),
    ]
