# Generated by Django 5.2.13 on 2026-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_add_trigram_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="spotify_playlist_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional Spotify playlist link for this workout.",
            ),
        ),
    ]
